# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: 20231103-165357-canary-harrier

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/


language: "vi"


# pipeline: null


# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
    number_additional_patterns: 10
  - name: RegexEntityExtractor
    # text will be processed with case insensitive as default
    case_sensitive: False
    # use lookup tables to extract entities
    use_lookup_tables: True
    # use regexes to extract entities
    use_regexes: False
    # use match word boundaries for lookup table
    use_word_boundaries: True
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 200
    ranking_length: 5
  - name: EntitySynonymMapper
  - name: FallbackClassifier
    threshold: 0.3
    ambiguity_threshold: 0.1
  - name: CRFEntityExtractor


# policies:
#   - name: MemoizationPolicy
#     max_history: 30
#     epochs: 200
#   - name: TEDPolicy
#     max_history: 30
#     epochs: 100
#   - name: RulePolicy
#     core_fallback_threshold: 0.4
#     core_fallback_action_name: 'action_default_fallback'
#     enable_fallback_prediction: True


# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
# No configuration for policies was provided. The following default policies were used to train your model.
# If you'd like to customize them, uncomment and adjust the policies.
# See https://rasa.com/docs/rasa/policies for more information.
  - name: MemoizationPolicy
    max_history: 60
    epochs: 200
  - name: RulePolicy
  - name: UnexpecTEDIntentPolicy
    max_history: 0
    epochs: 100
  - name: TEDPolicy
    max_history: 0
    epochs: 100
    constrain_similarities: true
